# Generated by Django 6.0.1 on 2026-01-21 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='appointment',
            field=models.OneToOneField(limit_choices_to={'status': 'COMPLETED'}, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='doctor',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='patient',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
