# Generated by Django 6.0.1 on 2026-01-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_visit_appointment_alter_visit_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='visit',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
