# Generated by Django 6.0.1 on 2026-01-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_visit_is_finalized_alter_visit_clinical_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
    ]
