# Generated by Django 6.0.1 on 2026-01-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_visit_ai_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='ai_summary',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='is_finalized',
        ),
    ]
