# Generated by Django 6.0.1 on 2026-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_remove_visit_ai_summary_remove_visit_is_finalized'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
