# Generated by Django 6.0.1 on 2026-01-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='experience_years',
            field=models.IntegerField(),
        ),
    ]
